-- Drop all tables
DROP TABLE IF EXISTS Sales;
DROP TABLE IF EXISTS Order_Items;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Snacks;
DROP TABLE IF EXISTS Suppliers;
